name: estud_ai
description: 'Estud.ai - Plataforma de estudos'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.15
  lucide_icons: ^0.257.0
  lottie: ^3.3.1
  dotted_border: ^2.1.0
  fl_chart: ^0.70.2
  custom_refresh_indicator: ^4.0.1
  cupertino_icons: ^1.0.8
  simple_animations: ^5.0.0+3

  # State Management
  flutter_riverpod: ^2.6.1
  equatable: ^2.0.5

  # Storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.3
  path_provider: ^2.1.3

  # API
  dio: ^5.7.0
  http: ^1.2.2

  # Security
  crypto: ^3.0.6
  encrypt: ^5.0.3
  jwt_decode: ^0.3.1

  # Utils
  intl: ^0.19.0
  mask_text_input_formatter: ^2.9.0
  flutter_masked_text2: ^0.9.1
  email_validator: ^3.0.0
  device_info_plus: ^11.2.0
  universal_html: ^2.2.4
  async: ^2.12.0

  # File handling
  file_picker: ^9.0.2
  open_filex: ^4.4.0
  csv: ^6.0.0
  mime_type: ^1.0.1

  # DI
  get_it: ^8.0.3

  # Config
  flutter_dotenv: ^5.2.1

  # Launcher
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/
    - assets/lottie/
    - assets/icon/
    - assets/png/
    - .env

# Configuração do flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: false
  web:
    generate: true
    image_path: "logo-estud.ai.png"
  min_sdk_android: 21
  adaptive_icon_background: "#00B894"
  adaptive_icon_foreground: "logo-estud.ai.png"
  image_path: "logo-estud.ai.png"
